### ISSUE TITLE
docker-compose file is missing on clean install

### ISSUE THREAD

**Issue by hphoeksma** [flownative/localbeach#22] opened 2020-11-05 15:12 UTC
Fresh install of 1.5.0+1, running beach start/down gives an error that the docker-compose.yml doesn't  exist.

Manually adding the file works.

**Comment by DavidSporer** [comment] 2020-11-10 14:30
I had the same error after an upgrade. Adding the file from here worked: https://github.com/flownative/localbeach/blob/master/~/Library/Application%20Support/Flownative/Local%20Beach/docker-compose.yml

**Comment by kdambekalns** [comment] 2020-11-16 20:54
This is essentially a duplicate of #21

**Closed by kdambekalns** 2020-11-16 20:54 UTC
